/**
 * Extract a struct/class and all its transitive field-type dependencies into a
 * single, self-contained `.d` file.
 *
 * This is driven by the `-extractTypes=<Name>` switch.  Only the data layout is
 * kept: fields are emitted, methods/constructors/templates/UDAs are dropped.  The
 * goal is to obtain an isolated module that mirrors the in-memory representation
 * of a type so introspection-based (de)serialization code can be tested without
 * recompiling the rest of the code base.
 *
 * The emitted module is written to stdout; redirect it to create the `.d` file:
 * ---
 * dmd -o- -extractTypes=Foo foo.d > Foo.d
 * ---
 *
 * Copyright:   Copyright (C) 1999-2025 by The D Language Foundation, All Rights Reserved
 * Authors:     $(LINK2 https://www.digitalmars.com, Walter Bright)
 * License:     $(LINK2 https://www.boost.org/LICENSE_1_0.txt, Boost License 1.0)
 * Source:      $(LINK2 https://github.com/dlang/dmd/blob/master/compiler/src/dmd/extracttypes.d, _extracttypes.d)
 * Documentation:  https://dlang.org/phobos/dmd_extracttypes.html
 */

module dmd.extracttypes;

import core.stdc.stdio;

import dmd.aggregate;
import dmd.arraytypes;
import dmd.dclass;
import dmd.declaration;
import dmd.denum;
import dmd.dmodule;
import dmd.dstruct;
import dmd.dsymbol;
import dmd.errorsink;
import dmd.globals;
import dmd.hdrgen;
import dmd.identifier;
import dmd.location;
import dmd.mtype;
import dmd.typesem : nextOf;
import dmd.root.array;
import dmd.common.outbuffer;

/**
 * Emit `typeName` together with every aggregate/enum reachable through its
 * fields as a single isolated module.
 *
 * Params:
 *      modules  = all root modules being compiled, searched for `typeName`
 *      typeName = name of the struct/class to extract
 *      eSink    = where to report errors
 * Returns: `true` on error
 */
bool extractTypes(ref Modules modules, const(char)[] typeName, ErrorSink eSink)
{
    // Find the requested aggregate among the compiled modules
    AggregateDeclaration root;
    foreach (m; modules)
    {
        if (auto ad = searchAggregate(m.members, typeName))
        {
            root = ad;
            break;
        }
    }
    if (!root)
    {
        eSink.error(Loc.initial, "type `%.*s` for `-extractTypes` not found",
            cast(int) typeName.length, typeName.ptr);
        return true;
    }

    // Collect `root` and all of its transitive field-type dependencies
    Collector c;
    c.addAggregate(root);

    // Emit the result.  AST nodes (fields, enums) are rendered through hdrgen
    // so the output matches dmd's own pretty-printer.
    OutBuffer buf;
    buf.doindent = true;
    HdrGenState hgs;
    buf.writestring("// Generated by `dmd -extractTypes=");
    buf.writestring(typeName);
    buf.writestring("` - fields only, methods stripped.");
    buf.writenl();
    foreach (s; c.order[])
    {
        if (auto ed = s.isEnumDeclaration())
            emitEnum(buf, ed, hgs);
        else if (auto ad = s.isAggregateDeclaration())
            emitAggregate(buf, ad, c, hgs);
    }

    fwrite(buf[].ptr, 1, buf.length, stdout);
    return false;
}

private:

/// Recursively search a member list for an aggregate named `name`
AggregateDeclaration searchAggregate(Dsymbols* members, const(char)[] name)
{
    if (!members)
        return null;
    foreach (s; *members)
    {
        if (auto ad = s.isAggregateDeclaration())
        {
            if (ad.ident && ad.ident.toString() == name)
                return ad;
        }
        // Recurse into nested scopes (template instances, nested aggregates, ...)
        if (auto sds = s.isScopeDsymbol())
        {
            if (auto found = searchAggregate(sds.members, name))
                return found;
        }
    }
    return null;
}

/// Gathers the set of symbols to emit, in discovery order, de-duplicated.
struct Collector
{
    bool[void*] seen;
    Array!Dsymbol order;

    void addAggregate(AggregateDeclaration ad)
    {
        if (!ad || (cast(void*) ad in seen))
            return;
        seen[cast(void*) ad] = true;
        order.push(ad);

        // Keep the inheritance chain so inherited fields are introspectable
        if (auto cd = ad.isClassDeclaration())
        {
            if (cd.baseClass && cd.baseClass !is ClassDeclaration.object)
                addAggregate(cd.baseClass);
        }

        foreach (vd; ad.fields)
            addType(vd.type);
    }

    void addEnum(EnumDeclaration ed)
    {
        if (!ed || (cast(void*) ed in seen))
            return;
        seen[cast(void*) ed] = true;
        order.push(ed);
        if (ed.memtype)
            addType(ed.memtype);
    }

    /// Follow a type down to the aggregates/enums it depends on
    void addType(Type t)
    {
        if (!t)
            return;
        if (auto ts = t.isTypeStruct())
            addAggregate(ts.sym);
        else if (auto tc = t.isTypeClass())
            addAggregate(tc.sym);
        else if (auto te = t.isTypeEnum())
            addEnum(te.sym);
        else if (auto ta = t.isTypeAArray())
        {
            addType(ta.index);
            addType(ta.next);
        }
        else if (auto n = t.nextOf()) // pointer, slice, static array
            addType(n);
    }

    bool isEmitted(AggregateDeclaration ad)
    {
        return ad && (cast(void*) ad in seen) !is null;
    }
}

void emitAggregate(ref OutBuffer buf, AggregateDeclaration ad, ref Collector c, ref HdrGenState hgs)
{
    buf.writenl();
    if (auto cd = ad.isClassDeclaration())
    {
        buf.writestring("class ");
        buf.writestring(ad.ident.toString());
        // Only keep the base if it is part of the emitted set
        if (cd.baseClass && c.isEmitted(cd.baseClass))
        {
            buf.writestring(" : ");
            buf.writestring(cd.baseClass.ident.toString());
        }
    }
    else if (ad.isUnionDeclaration())
    {
        buf.writestring("union ");
        buf.writestring(ad.ident.toString());
    }
    else
    {
        buf.writestring("struct ");
        buf.writestring(ad.ident.toString());
    }
    buf.writenl();
    buf.writeByte('{');
    buf.writenl();
    buf.level++;
    // Render each field as D code via hdrgen, dropping methods entirely
    foreach (vd; ad.fields)
        toCBuffer(vd, buf, hgs);
    buf.level--;
    buf.writeByte('}');
    buf.writenl();
}

void emitEnum(ref OutBuffer buf, EnumDeclaration ed, ref HdrGenState hgs)
{
    buf.writenl();
    buf.writestring("enum ");
    buf.writestring(ed.ident.toString());
    if (ed.memtype)
    {
        buf.writestring(" : ");
        toCBuffer(ed.memtype, buf, null, hgs);
    }
    buf.writenl();
    buf.writeByte('{');
    buf.writenl();
    buf.level++;
    if (ed.members)
    {
        foreach (s; *ed.members)
        {
            auto em = s.isEnumMember();
            if (!em)
                continue;
            buf.writestring(em.ident.toString());
            // Use the original (pre-semantic) value so the rendered member is
            // valid D source, not a `cast(...)` of the resolved constant.
            if (em.origValue)
            {
                buf.writestring(" = ");
                toCBuffer(em.origValue, buf, hgs);
            }
            buf.writeByte(',');
            buf.writenl();
        }
    }
    buf.level--;
    buf.writeByte('}');
    buf.writenl();
}
