/**
 * Extract a struct/class and all its transitive field-type dependencies into a
 * single, self-contained `.d` file.
 *
 * This is driven by the `-extractTypes=<Name>` switch.  Only the data layout is
 * kept: fields (and their user-defined attributes) are emitted, while methods,
 * constructors and templates are dropped.  The goal is to obtain an isolated
 * module that mirrors the in-memory representation of a type so introspection-
 * based (de)serialization code can be tested without recompiling the rest of the
 * code base.
 *
 * The emitted module is written to stdout; redirect it to create the `.d` file:
 * ---
 * dmd -o- -extractTypes=Foo foo.d > Foo.d
 * ---
 *
 * Rather than stringifying declarations by hand, this module builds a stripped
 * copy of each declaration's AST (keeping only the fields and UDAs) and hands it
 * to `dmd.hdrgen` for printing, so the output matches dmd's own pretty-printer.
 *
 * Copyright:   Copyright (C) 1999-2025 by The D Language Foundation, All Rights Reserved
 * Authors:     $(LINK2 https://www.digitalmars.com, Walter Bright)
 * License:     $(LINK2 https://www.boost.org/LICENSE_1_0.txt, Boost License 1.0)
 * Source:      $(LINK2 https://github.com/dlang/dmd/blob/master/compiler/src/dmd/extracttypes.d, _extracttypes.d)
 * Documentation:  https://dlang.org/phobos/dmd_extracttypes.html
 */

module dmd.extracttypes;

import core.stdc.stdio;

import dmd.aggregate;
import dmd.arraytypes;
import dmd.attrib;
import dmd.dclass;
import dmd.declaration;
import dmd.denum;
import dmd.dmodule;
import dmd.dstruct;
import dmd.dsymbol;
import dmd.errorsink;
import dmd.expression;
import dmd.globals;
import dmd.hdrgen;
import dmd.identifier;
import dmd.location;
import dmd.mtype;
import dmd.typesem : nextOf;
import dmd.root.array;
import dmd.common.outbuffer;

/**
 * Emit `typeName` together with every aggregate/enum reachable through its
 * fields (and field/aggregate UDAs) as a single isolated module.
 *
 * Params:
 *      modules  = all root modules being compiled, searched for `typeName`
 *      typeName = name of the struct/class to extract
 *      eSink    = where to report errors
 * Returns: `true` on error
 */
bool extractTypes(ref Modules modules, const(char)[] typeName, ErrorSink eSink)
{
    // Find the requested aggregate among the compiled modules
    AggregateDeclaration root;
    foreach (m; modules)
    {
        if (auto ad = searchAggregate(m.members, typeName))
        {
            root = ad;
            break;
        }
    }
    if (!root)
    {
        eSink.error(Loc.initial, "type `%.*s` for `-extractTypes` not found",
            cast(int) typeName.length, typeName.ptr);
        return true;
    }

    // Collect `root` and all of its transitive dependencies
    Collector c;
    c.addAggregate(root);

    // Build a stripped AST for each collected symbol and let hdrgen print it,
    // so the output matches dmd's own pretty-printer.
    OutBuffer buf;
    buf.doindent = true;
    HdrGenState hgs;
    buf.writestring("// Generated by `dmd -extractTypes=");
    buf.writestring(typeName);
    buf.writestring("` - fields only, methods stripped.");
    buf.writenl();
    foreach (s; c.order[])
    {
        buf.writenl();
        Dsymbol stripped;
        if (auto ed = s.isEnumDeclaration())
            stripped = stripEnum(ed);
        else if (auto ad = s.isAggregateDeclaration())
            stripped = stripAggregate(ad, c);
        if (stripped)
            toCBuffer(stripped, buf, hgs);
    }

    fwrite(buf[].ptr, 1, buf.length, stdout);
    return false;
}

private:

/// Recursively search a member list for an aggregate named `name`
AggregateDeclaration searchAggregate(Dsymbols* members, const(char)[] name)
{
    if (!members)
        return null;
    foreach (s; *members)
    {
        if (auto ad = s.isAggregateDeclaration())
        {
            if (ad.ident && ad.ident.toString() == name)
                return ad;
        }
        // Recurse into nested scopes (template instances, nested aggregates, ...)
        if (auto sds = s.isScopeDsymbol())
        {
            if (auto found = searchAggregate(sds.members, name))
                return found;
        }
        // Recurse into attribute declarations (e.g. `@UDA class Shape {}`)
        if (auto attr = s.isAttribDeclaration())
        {
            if (auto found = searchAggregate(attr.decl, name))
                return found;
        }
    }
    return null;
}

/// Gathers the set of symbols to emit, in discovery order, de-duplicated.
struct Collector
{
    bool[void*] seen;
    Array!Dsymbol order;

    void addAggregate(AggregateDeclaration ad)
    {
        if (!ad || (cast(void*) ad in seen))
            return;
        seen[cast(void*) ad] = true;
        order.push(ad);

        // Keep the inheritance chain so inherited fields are introspectable
        if (auto cd = ad.isClassDeclaration())
        {
            if (cd.baseClass && cd.baseClass !is ClassDeclaration.object)
                addAggregate(cd.baseClass);
        }

        addUdas(ad);
        foreach (vd; ad.fields)
        {
            addType(vd.type);
            addUdas(vd);
        }
    }

    void addEnum(EnumDeclaration ed)
    {
        if (!ed || (cast(void*) ed in seen))
            return;
        seen[cast(void*) ed] = true;
        order.push(ed);
        addUdas(ed);
        if (ed.memtype)
            addType(ed.memtype);
    }

    /// Follow a type down to the aggregates/enums it depends on
    void addType(Type t)
    {
        if (!t)
            return;
        if (auto ts = t.isTypeStruct())
            addAggregate(ts.sym);
        else if (auto tc = t.isTypeClass())
            addAggregate(tc.sym);
        else if (auto te = t.isTypeEnum())
            addEnum(te.sym);
        else if (auto ta = t.isTypeAArray())
        {
            addType(ta.index);
            addType(ta.next);
        }
        else if (auto n = t.nextOf()) // pointer, slice, static array
            addType(n);
    }

    /// Collect types referenced by the UDAs attached to `sym`
    void addUdas(Dsymbol sym)
    {
        if (!sym.userAttribDecl || !sym.userAttribDecl.atts)
            return;
        foreach (e; *sym.userAttribDecl.atts)
            addUdaExpr(e);
    }

    void addUdaExpr(Expression e)
    {
        if (!e)
            return;
        if (auto te = e.isTupleExp())
        {
            if (te.exps)
                foreach (sub; *te.exps)
                    addUdaExpr(sub);
        }
        else
            addType(e.type);
    }

    bool isEmitted(AggregateDeclaration ad)
    {
        return ad && (cast(void*) ad in seen) !is null;
    }
}

/**
 * Wrap `inner` in a `@(...)` UDA declaration if `src` carries user-defined
 * attributes, so hdrgen re-emits them.  Otherwise return `inner` unchanged.
 */
Dsymbol withUdas(Dsymbol inner, Dsymbol src)
{
    if (src.userAttribDecl && src.userAttribDecl.atts && src.userAttribDecl.atts.length)
        return new UserAttributeDeclaration(src.userAttribDecl.atts, new Dsymbols(inner));
    return inner;
}

/// Build a stripped copy of `ad` containing only its fields (and their UDAs).
Dsymbol stripAggregate(AggregateDeclaration ad, ref Collector c)
{
    auto members = new Dsymbols();
    foreach (vd; ad.fields)
        members.push(withUdas(vd, vd));

    AggregateDeclaration decl;
    if (auto cd = ad.isClassDeclaration())
    {
        auto baseclasses = new BaseClasses();
        // Only keep the base if it is part of the emitted set
        if (cd.baseClass && c.isEmitted(cd.baseClass))
            baseclasses.push(new BaseClass(cd.baseClass.type));
        decl = new ClassDeclaration(ad.loc, ad.ident, baseclasses, members, false);
    }
    else if (ad.isUnionDeclaration())
    {
        decl = new UnionDeclaration(ad.loc, ad.ident);
        decl.members = members;
    }
    else
    {
        decl = new StructDeclaration(ad.loc, ad.ident, false);
        decl.members = members;
    }
    return withUdas(decl, ad);
}

/// Build a stripped copy of `ed` using pre-semantic member values.
Dsymbol stripEnum(EnumDeclaration ed)
{
    auto decl = new EnumDeclaration(ed.loc, ed.ident, ed.memtype);
    decl.members = new Dsymbols();
    if (ed.members)
    {
        foreach (s; *ed.members)
        {
            if (auto em = s.isEnumMember())
            {
                // Use the original (pre-semantic) value so the rendered member
                // is valid D source, not a `cast(...)` of the resolved constant.
                decl.members.push(new EnumMember(em.loc, em.ident, em.origValue, null));
            }
        }
    }
    return withUdas(decl, ed);
}
