#!/bin/sh
# Build the DMD frontend to WebAssembly
# Run from the dmd repo root: ./compiler/wasm/build.sh
#
#   BACKEND=dmd  (default) host compiler is dmd's own wasm backend, linking the
#                real druntime + Phobos wasm archive.
#   BACKEND=ldc  legacy path: ldc2/ldmd2 with the minimal freestanding runtime in
#                rthooks.d and the core.* shims in shim/. Kept working, not default.
set -e

DMD_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$DMD_ROOT"

BACKEND="${BACKEND:-dmd}"
DRT="$DMD_ROOT/druntime/src"
PHOBOS_ROOT="${PHOBOS_ROOT:-/home/dennis/repos/phobos}"
OUT="$DMD_ROOT/compiler/wasm/dmd.wasm"

# --- Generate the embedded standard-library source table -----------------------
# Bake every regular druntime + phobos .d source (including the real object.d)
# into the wasm data section and register it in the frontend's FileManager at
# runtime
EMBED="$DMD_ROOT/compiler/wasm/druntime_embed.d"
emit_root() {
  # $1 = absolute root dir; remaining args = subdirs (relative to root) to scan.
  _root="$1"; shift
  ( cd "$_root" && find "$@" -name '*.d' | sed 's|^\./||' | sort | while IFS= read -r f; do
      printf '    EF("%s", cast(immutable(ubyte)[])(import("%s") ~ "\\0")),\n' "$f" "$f"
    done )
}
{
  echo "// GENERATED by compiler/wasm/build.sh -- do not edit."
  echo "module druntime_embed;"
  echo "import dmd.root.filename : FileName;"
  echo "import dmd.globals : global;"
  echo "private struct EF { string name; immutable(ubyte)[] data; }"
  echo "private static immutable EF[] files = ["
  emit_root "$DRT" .            # druntime: core/, rt/, gc/, object.d, ...
  emit_root "$PHOBOS_ROOT" std etc  # phobos import roots
  echo "];"
  # Each blob carries a trailing NUL the lexer needs as a sentinel, but the
  # registered length excludes it so the source itself ends where the file does.
  echo "void registerDruntime() { foreach (ref f; files) global.fileManager.add(FileName(f.name), f.data[0 .. \$ - 1]); }"
} > "$EMBED"

# Binaryen shrinks the module substantially and is what makes the download
# reasonable; -Oz also drops the name section, so set WASM_OPT_FLAGS=-O2 (or
# WASM_OPT=true to skip it) when you need readable wasmtime backtraces.
run_wasm_opt() {
  if command -v "${WASM_OPT:-wasm-opt}" >/dev/null 2>&1; then
    "${WASM_OPT:-wasm-opt}" ${WASM_OPT_FLAGS:--Oz} "$OUT" -o "$OUT"
  else
    echo "wasm-opt not found; shipping the unoptimized module" >&2
  fi
}

SRC="compiler/wasm/dmdwasm.d compiler/wasm/dmdwasm_lexdump.d compiler/wasm/dmdwasm_irdump.d compiler/wasm/druntime_embed.d"

# Symbols JS reaches into. __wasm_call_ctors and dmdwasm_init bring the instance
# up; the rest are the compile entry point and the output-buffer accessors.
EXPORTS="--export=__wasm_call_ctors --export=dmdwasm_init \
  --export=dmdwasm_run --export=dmdwasm_input_buffer --export=dmdwasm_errors \
  --export=dmdwasm_ast_ptr --export=dmdwasm_ast_len \
  --export=dmdwasm_parse_ptr --export=dmdwasm_parse_len \
  --export=dmdwasm_sema_ptr --export=dmdwasm_sema_len \
  --export=dmdwasm_lex_ptr --export=dmdwasm_lex_len \
  --export=dmdwasm_ir_ptr --export=dmdwasm_ir_len \
  --export=dmdwasm_iropt_ptr --export=dmdwasm_iropt_len \
  --export=dmdwasm_selftest --export=dmdwasm_run_stdin \
  --export=dmdwasm_build --export=dmdwasm_wasm_ptr --export=dmdwasm_wasm_len \
  --export=dmdwasm_wat"

# The Run button compiles a snippet to a second wasm module that shares this
# module's linear memory and calls its libc, so every libc function a
# whole-program druntime build imports has to be exported here. malloc/free also
# reserve the region the snippet's data and shadow stack live in.
LIBC_EXPORTS="malloc free calloc realloc memcpy memmove memset memcmp \
  printf fprintf snprintf sscanf fwrite fflush fgetwc fputwc write \
  strlen strerror strtod isspace isdigit toupper qsort abort exit getenv chdir \
  dlsym sysconf nanosleep sched_yield clock_getres clock_gettime __errno_location \
  pthread_self pthread_detach pthread_join pthread_create pthread_setcancelstate \
  pthread_attr_init pthread_attr_setstacksize pthread_attr_destroy \
  pthread_mutex_init pthread_mutex_destroy pthread_mutex_lock \
  pthread_mutex_unlock pthread_mutex_trylock \
  pthread_mutexattr_init pthread_mutexattr_settype pthread_mutexattr_destroy \
  _pthread_cleanup_push _pthread_cleanup_pop \
  fclose freopen fdopen feof ferror clearerr fsync fseeko ftello rewind setvbuf \
  fcntl fileno fwide fputc fputs putchar ungetc fgetc fgets getdelim fopen fread \
  strerror_r strcmp strncmp strcpy strncpy strchr strstr strtol strtoul strtof \
  memchr vsnprintf puts atoi \
  cbrt fmod modf remainder remquo nearbyint round llround lround trunc floor ceil \
  log log2 log10 log1p exp exp2 expm1 pow sqrt ldexp ldexpf frexp rint rintf \
  llrint lrint cos cosf sin sinf tan tanf acos asin atan atan2 cosh sinh tanh \
  fabs fmin fmax hypot"

for f in $LIBC_EXPORTS; do EXPORTS="$EXPORTS --export-if-defined=$f"; done

case "$BACKEND" in
dmd)
  DMD="${DMD:-$DMD_ROOT/generated/linux/release/64/dmd}"
  # WASI has no mmap; wasi-libc ships a malloc-backed emulation that
  # dmd.common.file's FileMapping links against (dead code in the browser, but it
  # has to resolve).
  "$DMD" -mwasm32 ${DMD_OPT--O} -version=WASI_EMULATED_MMAN \
    -i=dmd -i=druntime_embed \
    -Icompiler/src \
    -J. -Jcompiler/src/dmd/res -Jcompiler/wasm -J"$DRT" -J"$PHOBOS_ROOT" \
    -L-l:libwasi-emulated-mman.a \
    $(for e in $EXPORTS; do printf -- '-L%s ' "$e"; done) \
    -od=compiler/wasm/obj -of="$OUT" \
    $SRC "$@"
  run_wasm_opt
  ;;
ldc)
  WASI_LIBC="${WASI_LIBC:-/home/dennis/repos1/wasi-libc/sysroot/lib/wasm32-wasi/libc.a}"
  RTLIB="$DMD_ROOT/compiler/wasm/lib/libcompiler-rt-wasm.a"
  ldmd2 -mtriple=wasm32-unknown-unknown-wasi -defaultlib= -version=MinimalRuntime \
    -L-allow-undefined -L"$WASI_LIBC" -L"$RTLIB" -L--no-entry \
    $(for e in $EXPORTS; do printf -- '-L%s ' "$e"; done) \
    -Oz \
    -J. -Jcompiler/src/dmd/res -Jcompiler/wasm -J"$DRT" -J"$PHOBOS_ROOT" \
    -i -Icompiler/wasm/shim -Icompiler/src -I"$DRT" -i=core -i=rt -i=dmd \
    compiler/wasm/rthooks.d $SRC \
    -of="$OUT" "$@"
  run_wasm_opt
  ;;
*)
  echo "unknown BACKEND=$BACKEND (expected 'dmd' or 'ldc')" >&2
  exit 1
  ;;
esac

# Publish the built module to the web harness so `web/` is self-contained.
cp "$OUT" compiler/wasm/web/dmd.wasm
ls -la compiler/wasm/web/dmd.wasm
