#!/bin/sh
# Build the DMD frontend to WebAssembly
# Run from the dmd repo root: ./compiler/wasm/build.sh
set -e

DMD_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$DMD_ROOT"

WASI_LIBC="${WASI_LIBC:-/home/dennis/repos1/wasi-libc/sysroot/lib/wasm32-wasi/libc.a}"
RTLIB="$DMD_ROOT/compiler/wasm/lib/libcompiler-rt-wasm.a"
DRT="$DMD_ROOT/druntime/src"
PHOBOS_ROOT="${PHOBOS_ROOT:-/home/dennis/repos/phobos}"

# --- Generate the embedded standard-library source table -----------------------
# Bake every regular druntime + phobos .d source (including the real object.d)
# into the wasm data section and register it in the frontend's FileManager at
# runtime
EMBED="$DMD_ROOT/compiler/wasm/druntime_embed.d"
emit_root() {
  # $1 = absolute root dir; remaining args = subdirs (relative to root) to scan.
  _root="$1"; shift
  ( cd "$_root" && find "$@" -name '*.d' | sed 's|^\./||' | sort | while IFS= read -r f; do
      printf '    EF("%s", import("%s")),\n' "$f" "$f"
    done )
}
{
  echo "// GENERATED by compiler/wasm/build.sh -- do not edit."
  echo "module druntime_embed;"
  echo "import dmd.root.filename : FileName;"
  echo "import dmd.globals : global;"
  echo "private struct EF { string name; immutable(ubyte)[] data; }"
  echo "private static immutable EF[] files = ["
  emit_root "$DRT" .            # druntime: core/, rt/, gc/, object.d, ...
  emit_root "$PHOBOS_ROOT" std etc  # phobos import roots
  echo "];"
  echo "void registerDruntime() { foreach (ref f; files) global.fileManager.add(FileName(f.name), f.data); }"
} > "$EMBED"

ldmd2 -mtriple=wasm32-unknown-unknown-wasi -defaultlib= \
  -L-allow-undefined -L"$WASI_LIBC" -L"$RTLIB" -L--no-entry \
  -L--export=dmdwasm_run -L--export=dmdwasm_ast_ptr -L--export=dmdwasm_ast_len \
  -L--export=dmdwasm_parse_ptr -L--export=dmdwasm_parse_len \
  -L--export=dmdwasm_sema_ptr -L--export=dmdwasm_sema_len \
  -L--export=dmdwasm_lex_ptr -L--export=dmdwasm_lex_len \
  -L--export=dmdwasm_ir_ptr -L--export=dmdwasm_ir_len \
  -L--export=dmdwasm_iropt_ptr -L--export=dmdwasm_iropt_len \
  -L--export=dmdwasm_errors -L--export=dmdwasm_input_buffer -L--export=dmdwasm_selftest -L--export=dmdwasm_run_stdin -L--export=__wasm_call_ctors \
  -Oz \
  -J. -Jcompiler/src/dmd/res -Jcompiler/wasm -J"$DRT" -J"$PHOBOS_ROOT" \
  -i -Icompiler/wasm/shim -Icompiler/src -I"$DRT" -i=core -i=rt -i=dmd \
  compiler/wasm/dmdwasm.d compiler/wasm/dmdwasm_lexdump.d compiler/wasm/dmdwasm_irdump.d compiler/wasm/rthooks.d compiler/wasm/druntime_embed.d \
  -of=compiler/wasm/dmd.wasm "$@"

# Publish the built module to the web harness so `web/` is self-contained.
cp compiler/wasm/dmd.wasm compiler/wasm/web/dmd.wasm
