/**
 * WASM runtime entry point and _d_run_main implementation.
 *
 * Provides the _d_run_main hook that the compiler-generated C main calls, and
 * no-op stubs for module-info registration (Phase 5 will replace these with a
 * real implementation once minfo section support lands).
 *
 * Copyright: Copyright (C) 1999-2026 by The D Language Foundation, All Rights Reserved
 * License:   $(LINK2 https://www.boost.org/LICENSE_1_0.txt, Boost License 1.0)
 */
module rt.wasm.start;

import core.stdc.stdlib : exit;

nothrow:
extern (C):

// Provided by rt/wasm/gc.d
void gc_init();
void gc_term();

// ── WASI _start entry point ───────────────────────────────────────────────────
// wasmtime (WASI command ABI) calls _start, not main.  proc_exit called from
// _start correctly propagates the exit code to the shell; called from main it
// does not (wasmtime exits 0 regardless of the argument).  We therefore
// provide _start here which calls the C main and then proc_exits its result.
//
// The C main is generated by core/internal/entrypoint.d as:
//   extern(C) int main(int argc, char** argv)
// We call it with argc=0, argv=null.
private extern(C) int main_fn(int argc, char** argv) nothrow
{
    // forward-declared below as `main`; alias avoids a D-level `main` symbol
    return 0; // never reached, just satisfies noreturn path below
}

// Declare the compiler-generated C main under the external name "main".
// Using pragma(mangle) to avoid clashing with D's special 'main' treatment.
pragma(mangle, "main") private extern(C) int __wasm_rt_main(int, char**) nothrow;

// wasm-ld synthesizes __wasm_call_ctors from object .init_array / .ctors and
// .Linking custom-section init functions.  wasi-libc relies on it to set up
// stdio buffers (FILE* for stdout/stderr) before any printf can succeed.
private extern(C) void __wasm_call_ctors() @nogc nothrow;
private extern(C) void __wasm_call_dtors() @nogc nothrow;

export void _start() nothrow
{
    __wasm_call_ctors();
    int rc = __wasm_rt_main(0, null);
    __wasm_call_dtors();
    proc_exit(rc);
    while (true) {}
}

// ── Module constructor stubs (Phase 5) ────────────────────────────────────────
// Replaced once the minfo section / ModuleInfo iteration is wired up.

void rt_moduleCtor()  {}
void rt_moduleDtor()  {}
void rt_moduleTlsCtor() @nogc {}
void rt_moduleTlsDtor() @nogc {}

// ── _d_run_main ───────────────────────────────────────────────────────────────
// Called by the compiler-generated C main(argc, argv).
// mainFunc is a WASM table index for _Dmain — we ignore it and call _Dmain
// directly by name to avoid the function-pointer call_indirect path.
private extern(C) int _Dmain(char[][] args) nothrow;

int _d_run_main(int argc, char** argv, void* mainFunc)
{
    gc_init();
    rt_moduleCtor();
    int result = _Dmain(null); // empty args for now (no WASI argv yet)
    rt_moduleDtor();
    gc_term();
    return result;
}

// ── _d_initMonoTime stub ──────────────────────────────────────────────────────
void _d_initMonoTime() @nogc {}

// ── WASI abort helper (single proc_exit import across the whole runtime) ──────

import core.attribute : wasmImportModule;

// WASI proc_exit: (i32) -> () — terminates the process, never returns.
// Single declaration avoids duplicate-import linker errors.
@wasmImportModule("wasi_snapshot_preview1")
private extern(C) void proc_exit(int code) @nogc nothrow;

noreturn _wasm_trap(int code) @nogc nothrow
{
    proc_exit(code);
    while (true) {} // noreturn: proc_exit never returns
}
